name: Build and deploy Node.js app to Azure Web App - qrxrq-backend
on:
  push:
    branches:
      - main
    paths:
      - 'qrxrq-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies, build, and test (Backend Only)
        run: |
          cd qrxrq-backend
          npm install
          npm run build --if-present          

      - name: Zip backend artifact for deployment
        run: |
          cd qrxrq-backend
          zip -r ../release.zip . 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-backend

      - name: Unzip backend artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A7AF39A9BAF4B18AB00C7F514C06CF2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55277A1BF2B445C0BEC64FDA8A2FB23C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2730771F3AC34130A4885B043B1032FD }}


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qrxrq'
          slot-name: 'Production'
          package: .
